# Site settings
title: blijblijblij.github.io
header-img: img/home-bg.jpg
email: rhwessel@xs4all.nl
description: "blablabla, pentaho, linux, docker, mesos..."
baseurl: ""
url: "https://blijblijblij.github.io"
twitter_username: blijblijblij
github_username:  blijblijblij
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
