BaseUrl= "https://blijblijblij.github.io/"
LanguageCode= "en-US"
Title= "blijblijblij.github.io"
paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "... blablabla, linux, pentaho, docker, mesos ..."
  cover = "images/cover.jpg"
  author = "Rogier Wessel"
  authorlocation = "Amersfoort, The Netherlands"
  authorwebsite = "http://blijblijblij.github.io"
  bio= "Opensource Data dude, from linux to docker into the magical world of data and Pentaho. Might have eaten all red pills when it came to docker..."
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://blijblijblij.github.io/feed.xml"
  githubName = "blijblijblij"
  twitterName = "blijblijblij"
  skypeName = "blijblijblij"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true

  # [[menu.main]]
  #   name = "My Blog"
  #   weight = -120
  #   identifier = "blog"
  #   url = "/"
  #
  # [[menu.main]]
  #   name = "About me"
  #   weight = -110
  #   identifier = "about"
  #   url = "/about"
