name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.59.1'

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
        CNAME: blog.blijblijblij.com

      # - name: Deploy the site
      #   uses: benmatselby/hugo-deploy-gh-pages@master
      #   env:
      #     HUGO_VERSION: 0.57.2
      #     TARGET_REPO: blijblijblij/blog.blijblijblij.com
      #     TOKEN: ${{ secrets.TOKEN }}
      #     # HUGO_ARGS: '-d docs #-t kiss'
      #     CNAME: blog.blijblijblij.com
